// Generated by CoffeeScript 1.10.0
(function() {
  var fs, main, yaml;

  yaml = require('js-yaml');

  fs = require('fs');

  main = function() {
    var data;
    data = yaml.load(fs.readFileSync(process.argv[2], "utf8"));
    return process.stdout.write("__complete-shell::" + data.cmd + "() {\n  echo \"" + (data.sub.join(' ')) + "\"\n}");
  };

  main();

}).call(this);
